apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deployment
spec:
  template:
    spec:
      containers:
      - name: meu-container
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "1000m"