name: Docker Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build Docker image
    #   run: docker build -t josefavnss/nginx:latest .
    #   working-directory: ./path/to/your/dockerfile/directory

    # - name: Push Docker image
    #   run: docker push josefavnss/nginx:latest

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
         push: true
         context: .
         file: Dockerfile
         tags: josefavnss/nginx:latest